// flow-typed signature: 2496d48bd49cb503a055cb977ff48b63
// flow-typed version: <<STUB>>/auth0-js_v^9.4.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-js/build/auth0' {
  declare module.exports: any;
}

declare module 'auth0-js/build/auth0.min' {
  declare module.exports: any;
}

declare module 'auth0-js/build/cordova-auth0-plugin' {
  declare module.exports: any;
}

declare module 'auth0-js/build/cordova-auth0-plugin.min' {
  declare module.exports: any;
}

declare module 'auth0-js/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'auth0-js/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'auth0-js/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'auth0-js/gulpfile' {
  declare module.exports: any;
}

declare module 'auth0-js/integration/redirect_authorize.test' {
  declare module.exports: any;
}

declare module 'auth0-js/integration/selenium' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova/index' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova/plugin-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/plugins/cordova/popup-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/scripts/jsdocs' {
  declare module.exports: any;
}

declare module 'auth0-js/scripts/utils/attribute' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication/db-connection' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication/index' {
  declare module.exports: any;
}

declare module 'auth0-js/src/authentication/passwordless-authentication' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/assert' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/base64_url' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/cookies' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/error' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/iframe-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/object-assign' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/object' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/parameters-whitelist' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/plugins' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/popup-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/random' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/request-builder' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/response-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/ssodata' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/cookie' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/dummy' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/storage/handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/url' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/warn' {
  declare module.exports: any;
}

declare module 'auth0-js/src/helper/window' {
  declare module.exports: any;
}

declare module 'auth0-js/src/index' {
  declare module.exports: any;
}

declare module 'auth0-js/src/management/index' {
  declare module.exports: any;
}

declare module 'auth0-js/src/version' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/cross-origin-authentication' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/hosted-pages' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/index' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/popup' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/redirect' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/silent-authentication-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/transaction-manager' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/username-password' {
  declare module.exports: any;
}

declare module 'auth0-js/src/web-auth/web-message-handler' {
  declare module.exports: any;
}

declare module 'auth0-js/test/authentication/authentication.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/authentication/db-connection.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/authentication/passwordless.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/authentication/ro.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/assert.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/cookies.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/iframe-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/object.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/popup-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/random.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/request-builder.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/response-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/ssodata.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/storage-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/storage.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/warn.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/helper/window.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/management/management.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/mock/mock-auth0-plugin' {
  declare module.exports: any;
}

declare module 'auth0-js/test/mock/request-mock' {
  declare module.exports: any;
}

declare module 'auth0-js/test/plugins/cordova.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/setup' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/cross-origin-authentication.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/extensibility.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/hosted-pages.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/popup.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/redirect.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/silent-authentication-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/transaction-manager.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/web-auth/web-auth.test' {
  declare module.exports: any;
}

declare module 'auth0-js/webpack.config' {
  declare module.exports: any;
}

declare module 'auth0-js/webpack.prod.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-js/build/auth0.js' {
  declare module.exports: $Exports<'auth0-js/build/auth0'>;
}
declare module 'auth0-js/build/auth0.min.js' {
  declare module.exports: $Exports<'auth0-js/build/auth0.min'>;
}
declare module 'auth0-js/build/cordova-auth0-plugin.js' {
  declare module.exports: $Exports<'auth0-js/build/cordova-auth0-plugin'>;
}
declare module 'auth0-js/build/cordova-auth0-plugin.min.js' {
  declare module.exports: $Exports<'auth0-js/build/cordova-auth0-plugin.min'>;
}
declare module 'auth0-js/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'auth0-js/docs/scripts/linenumber'>;
}
declare module 'auth0-js/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'auth0-js/docs/scripts/prettify/lang-css'>;
}
declare module 'auth0-js/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'auth0-js/docs/scripts/prettify/prettify'>;
}
declare module 'auth0-js/gulpfile.js' {
  declare module.exports: $Exports<'auth0-js/gulpfile'>;
}
declare module 'auth0-js/integration/redirect_authorize.test.js' {
  declare module.exports: $Exports<'auth0-js/integration/redirect_authorize.test'>;
}
declare module 'auth0-js/integration/selenium.js' {
  declare module.exports: $Exports<'auth0-js/integration/selenium'>;
}
declare module 'auth0-js/plugins/cordova/index.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova/index'>;
}
declare module 'auth0-js/plugins/cordova/plugin-handler.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova/plugin-handler'>;
}
declare module 'auth0-js/plugins/cordova/popup-handler.js' {
  declare module.exports: $Exports<'auth0-js/plugins/cordova/popup-handler'>;
}
declare module 'auth0-js/scripts/jsdocs.js' {
  declare module.exports: $Exports<'auth0-js/scripts/jsdocs'>;
}
declare module 'auth0-js/scripts/utils/attribute.js' {
  declare module.exports: $Exports<'auth0-js/scripts/utils/attribute'>;
}
declare module 'auth0-js/src/authentication/db-connection.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication/db-connection'>;
}
declare module 'auth0-js/src/authentication/index.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication/index'>;
}
declare module 'auth0-js/src/authentication/passwordless-authentication.js' {
  declare module.exports: $Exports<'auth0-js/src/authentication/passwordless-authentication'>;
}
declare module 'auth0-js/src/helper/assert.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/assert'>;
}
declare module 'auth0-js/src/helper/base64_url.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/base64_url'>;
}
declare module 'auth0-js/src/helper/cookies.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/cookies'>;
}
declare module 'auth0-js/src/helper/error.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/error'>;
}
declare module 'auth0-js/src/helper/iframe-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/iframe-handler'>;
}
declare module 'auth0-js/src/helper/object-assign.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/object-assign'>;
}
declare module 'auth0-js/src/helper/object.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/object'>;
}
declare module 'auth0-js/src/helper/parameters-whitelist.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/parameters-whitelist'>;
}
declare module 'auth0-js/src/helper/plugins.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/plugins'>;
}
declare module 'auth0-js/src/helper/popup-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/popup-handler'>;
}
declare module 'auth0-js/src/helper/random.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/random'>;
}
declare module 'auth0-js/src/helper/request-builder.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/request-builder'>;
}
declare module 'auth0-js/src/helper/response-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/response-handler'>;
}
declare module 'auth0-js/src/helper/ssodata.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/ssodata'>;
}
declare module 'auth0-js/src/helper/storage.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage'>;
}
declare module 'auth0-js/src/helper/storage/cookie.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/cookie'>;
}
declare module 'auth0-js/src/helper/storage/dummy.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/dummy'>;
}
declare module 'auth0-js/src/helper/storage/handler.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/storage/handler'>;
}
declare module 'auth0-js/src/helper/url.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/url'>;
}
declare module 'auth0-js/src/helper/warn.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/warn'>;
}
declare module 'auth0-js/src/helper/window.js' {
  declare module.exports: $Exports<'auth0-js/src/helper/window'>;
}
declare module 'auth0-js/src/index.js' {
  declare module.exports: $Exports<'auth0-js/src/index'>;
}
declare module 'auth0-js/src/management/index.js' {
  declare module.exports: $Exports<'auth0-js/src/management/index'>;
}
declare module 'auth0-js/src/version.js' {
  declare module.exports: $Exports<'auth0-js/src/version'>;
}
declare module 'auth0-js/src/web-auth/cross-origin-authentication.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/cross-origin-authentication'>;
}
declare module 'auth0-js/src/web-auth/hosted-pages.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/hosted-pages'>;
}
declare module 'auth0-js/src/web-auth/index.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/index'>;
}
declare module 'auth0-js/src/web-auth/popup.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/popup'>;
}
declare module 'auth0-js/src/web-auth/redirect.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/redirect'>;
}
declare module 'auth0-js/src/web-auth/silent-authentication-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/silent-authentication-handler'>;
}
declare module 'auth0-js/src/web-auth/transaction-manager.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/transaction-manager'>;
}
declare module 'auth0-js/src/web-auth/username-password.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/username-password'>;
}
declare module 'auth0-js/src/web-auth/web-message-handler.js' {
  declare module.exports: $Exports<'auth0-js/src/web-auth/web-message-handler'>;
}
declare module 'auth0-js/test/authentication/authentication.test.js' {
  declare module.exports: $Exports<'auth0-js/test/authentication/authentication.test'>;
}
declare module 'auth0-js/test/authentication/db-connection.test.js' {
  declare module.exports: $Exports<'auth0-js/test/authentication/db-connection.test'>;
}
declare module 'auth0-js/test/authentication/passwordless.test.js' {
  declare module.exports: $Exports<'auth0-js/test/authentication/passwordless.test'>;
}
declare module 'auth0-js/test/authentication/ro.test.js' {
  declare module.exports: $Exports<'auth0-js/test/authentication/ro.test'>;
}
declare module 'auth0-js/test/helper/assert.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/assert.test'>;
}
declare module 'auth0-js/test/helper/cookies.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/cookies.test'>;
}
declare module 'auth0-js/test/helper/iframe-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/iframe-handler.test'>;
}
declare module 'auth0-js/test/helper/object.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/object.test'>;
}
declare module 'auth0-js/test/helper/popup-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/popup-handler.test'>;
}
declare module 'auth0-js/test/helper/random.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/random.test'>;
}
declare module 'auth0-js/test/helper/request-builder.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/request-builder.test'>;
}
declare module 'auth0-js/test/helper/response-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/response-handler.test'>;
}
declare module 'auth0-js/test/helper/ssodata.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/ssodata.test'>;
}
declare module 'auth0-js/test/helper/storage-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/storage-handler.test'>;
}
declare module 'auth0-js/test/helper/storage.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/storage.test'>;
}
declare module 'auth0-js/test/helper/warn.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/warn.test'>;
}
declare module 'auth0-js/test/helper/window.test.js' {
  declare module.exports: $Exports<'auth0-js/test/helper/window.test'>;
}
declare module 'auth0-js/test/management/management.test.js' {
  declare module.exports: $Exports<'auth0-js/test/management/management.test'>;
}
declare module 'auth0-js/test/mock/mock-auth0-plugin.js' {
  declare module.exports: $Exports<'auth0-js/test/mock/mock-auth0-plugin'>;
}
declare module 'auth0-js/test/mock/request-mock.js' {
  declare module.exports: $Exports<'auth0-js/test/mock/request-mock'>;
}
declare module 'auth0-js/test/plugins/cordova.test.js' {
  declare module.exports: $Exports<'auth0-js/test/plugins/cordova.test'>;
}
declare module 'auth0-js/test/setup.js' {
  declare module.exports: $Exports<'auth0-js/test/setup'>;
}
declare module 'auth0-js/test/web-auth/cross-origin-authentication.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/cross-origin-authentication.test'>;
}
declare module 'auth0-js/test/web-auth/extensibility.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/extensibility.test'>;
}
declare module 'auth0-js/test/web-auth/hosted-pages.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/hosted-pages.test'>;
}
declare module 'auth0-js/test/web-auth/popup.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/popup.test'>;
}
declare module 'auth0-js/test/web-auth/redirect.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/redirect.test'>;
}
declare module 'auth0-js/test/web-auth/silent-authentication-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/silent-authentication-handler.test'>;
}
declare module 'auth0-js/test/web-auth/transaction-manager.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/transaction-manager.test'>;
}
declare module 'auth0-js/test/web-auth/web-auth.test.js' {
  declare module.exports: $Exports<'auth0-js/test/web-auth/web-auth.test'>;
}
declare module 'auth0-js/webpack.config.js' {
  declare module.exports: $Exports<'auth0-js/webpack.config'>;
}
declare module 'auth0-js/webpack.prod.config.js' {
  declare module.exports: $Exports<'auth0-js/webpack.prod.config'>;
}
