// flow-typed signature: e3ec5b610565c823759063c63e2eebd8
// flow-typed version: <<STUB>>/react-app-rewire-less_v^2.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-app-rewire-less/index' {
  declare module.exports: $Exports<'react-app-rewire-less'>;
}
declare module 'react-app-rewire-less/index.js' {
  declare module.exports: $Exports<'react-app-rewire-less'>;
}
